# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layouts/base_project_main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_EMG = QtWidgets.QWidget()
        self.tab_EMG.setObjectName("tab_EMG")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_EMG)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayoutGraphStatus = QtWidgets.QVBoxLayout()
        self.verticalLayoutGraphStatus.setObjectName("verticalLayoutGraphStatus")
        self.verticalLayoutGraph = QtWidgets.QVBoxLayout()
        self.verticalLayoutGraph.setObjectName("verticalLayoutGraph")
        self.label_replace = QtWidgets.QLabel(self.tab_EMG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_replace.sizePolicy().hasHeightForWidth())
        self.label_replace.setSizePolicy(sizePolicy)
        self.label_replace.setObjectName("label_replace")
        self.verticalLayoutGraph.addWidget(self.label_replace)
        self.verticalLayoutGraphStatus.addLayout(self.verticalLayoutGraph)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_status = QtWidgets.QLabel(self.tab_EMG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_status.sizePolicy().hasHeightForWidth())
        self.lbl_status.setSizePolicy(sizePolicy)
        self.lbl_status.setObjectName("lbl_status")
        self.horizontalLayout_3.addWidget(self.lbl_status)
        self.cb_chart_emg_on_off = QtWidgets.QCheckBox(self.tab_EMG)
        self.cb_chart_emg_on_off.setChecked(True)
        self.cb_chart_emg_on_off.setObjectName("cb_chart_emg_on_off")
        self.horizontalLayout_3.addWidget(self.cb_chart_emg_on_off)
        self.verticalLayoutGraphStatus.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayoutGraphStatus)
        self.tabWidget.addTab(self.tab_EMG, "")
        self.tab_features = QtWidgets.QWidget()
        self.tab_features.setObjectName("tab_features")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_features)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayoutGraphStatus_features = QtWidgets.QVBoxLayout()
        self.verticalLayoutGraphStatus_features.setObjectName("verticalLayoutGraphStatus_features")
        self.verticalLayoutGraph_features = QtWidgets.QVBoxLayout()
        self.verticalLayoutGraph_features.setObjectName("verticalLayoutGraph_features")
        self.horizontalLayout_features = QtWidgets.QHBoxLayout()
        self.horizontalLayout_features.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_features.setObjectName("horizontalLayout_features")
        self.label_features = QtWidgets.QLabel(self.tab_features)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_features.sizePolicy().hasHeightForWidth())
        self.label_features.setSizePolicy(sizePolicy)
        self.label_features.setObjectName("label_features")
        self.horizontalLayout_features.addWidget(self.label_features)
        self.cb_features = QtWidgets.QComboBox(self.tab_features)
        self.cb_features.setEditable(False)
        self.cb_features.setObjectName("cb_features")
        self.horizontalLayout_features.addWidget(self.cb_features)
        self.checkBox = QtWidgets.QCheckBox(self.tab_features)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_features.addWidget(self.checkBox)
        self.verticalLayoutGraph_features.addLayout(self.horizontalLayout_features)
        self.label_replace_features = QtWidgets.QLabel(self.tab_features)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_replace_features.sizePolicy().hasHeightForWidth())
        self.label_replace_features.setSizePolicy(sizePolicy)
        self.label_replace_features.setObjectName("label_replace_features")
        self.verticalLayoutGraph_features.addWidget(self.label_replace_features)
        self.verticalLayoutGraphStatus_features.addLayout(self.verticalLayoutGraph_features)
        self.horizontalLayout_status_features = QtWidgets.QHBoxLayout()
        self.horizontalLayout_status_features.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_status_features.setObjectName("horizontalLayout_status_features")
        self.lbl_status_features = QtWidgets.QLabel(self.tab_features)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_status_features.sizePolicy().hasHeightForWidth())
        self.lbl_status_features.setSizePolicy(sizePolicy)
        self.lbl_status_features.setObjectName("lbl_status_features")
        self.horizontalLayout_status_features.addWidget(self.lbl_status_features)
        self.cb_chart_features_on_off = QtWidgets.QCheckBox(self.tab_features)
        self.cb_chart_features_on_off.setChecked(True)
        self.cb_chart_features_on_off.setObjectName("cb_chart_features_on_off")
        self.horizontalLayout_status_features.addWidget(self.cb_chart_features_on_off)
        self.verticalLayoutGraphStatus_features.addLayout(self.horizontalLayout_status_features)
        self.horizontalLayout_5.addLayout(self.verticalLayoutGraphStatus_features)
        self.tabWidget.addTab(self.tab_features, "")
        self.tab_classification = QtWidgets.QWidget()
        self.tab_classification.setObjectName("tab_classification")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_classification)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.graphicsView_classification = QtWidgets.QGraphicsView(self.tab_classification)
        self.graphicsView_classification.setObjectName("graphicsView_classification")
        self.horizontalLayout_6.addWidget(self.graphicsView_classification)
        self.tabWidget.addTab(self.tab_classification, "")
        self.tab_controle_manuel = QtWidgets.QWidget()
        self.tab_controle_manuel.setObjectName("tab_controle_manuel")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_controle_manuel)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_f1 = QtWidgets.QGroupBox(self.tab_controle_manuel)
        self.groupBox_f1.setObjectName("groupBox_f1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_f1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.h_slider_1 = QtWidgets.QSlider(self.groupBox_f1)
        self.h_slider_1.setMaximum(90)
        self.h_slider_1.setOrientation(QtCore.Qt.Horizontal)
        self.h_slider_1.setObjectName("h_slider_1")
        self.verticalLayout_11.addWidget(self.h_slider_1)
        self.verticalLayout_6.addWidget(self.groupBox_f1)
        self.groupBox_f2 = QtWidgets.QGroupBox(self.tab_controle_manuel)
        self.groupBox_f2.setObjectName("groupBox_f2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_f2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.h_slider_2 = QtWidgets.QSlider(self.groupBox_f2)
        self.h_slider_2.setMaximum(90)
        self.h_slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.h_slider_2.setObjectName("h_slider_2")
        self.verticalLayout_8.addWidget(self.h_slider_2)
        self.verticalLayout_6.addWidget(self.groupBox_f2)
        self.groupBox_f3 = QtWidgets.QGroupBox(self.tab_controle_manuel)
        self.groupBox_f3.setObjectName("groupBox_f3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_f3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.h_slider_3 = QtWidgets.QSlider(self.groupBox_f3)
        self.h_slider_3.setMaximum(90)
        self.h_slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.h_slider_3.setObjectName("h_slider_3")
        self.verticalLayout_9.addWidget(self.h_slider_3)
        self.verticalLayout_6.addWidget(self.groupBox_f3)
        self.groupBox_f4 = QtWidgets.QGroupBox(self.tab_controle_manuel)
        self.groupBox_f4.setObjectName("groupBox_f4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_f4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.h_slider_4 = QtWidgets.QSlider(self.groupBox_f4)
        self.h_slider_4.setMaximum(90)
        self.h_slider_4.setOrientation(QtCore.Qt.Horizontal)
        self.h_slider_4.setObjectName("h_slider_4")
        self.verticalLayout_10.addWidget(self.h_slider_4)
        self.verticalLayout_6.addWidget(self.groupBox_f4)
        self.groupBox_f5 = QtWidgets.QGroupBox(self.tab_controle_manuel)
        self.groupBox_f5.setObjectName("groupBox_f5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_f5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.h_slider_5 = QtWidgets.QSlider(self.groupBox_f5)
        self.h_slider_5.setMaximum(90)
        self.h_slider_5.setOrientation(QtCore.Qt.Horizontal)
        self.h_slider_5.setObjectName("h_slider_5")
        self.verticalLayout_4.addWidget(self.h_slider_5)
        self.verticalLayout_6.addWidget(self.groupBox_f5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_controle_manuel)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_laser = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_laser.setObjectName("btn_laser")
        self.horizontalLayout_10.addWidget(self.btn_laser)
        self.btn_reset_position = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_reset_position.setObjectName("btn_reset_position")
        self.horizontalLayout_10.addWidget(self.btn_reset_position)
        self.btn_close_position = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_close_position.setObjectName("btn_close_position")
        self.horizontalLayout_10.addWidget(self.btn_close_position)
        self.btn_send_position = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_send_position.setObjectName("btn_send_position")
        self.horizontalLayout_10.addWidget(self.btn_send_position)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_controle_manuel, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_settings)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_settings)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.cb_in_serial_port = QtWidgets.QComboBox(self.groupBox_10)
        self.cb_in_serial_port.setObjectName("cb_in_serial_port")
        self.horizontalLayout_13.addWidget(self.cb_in_serial_port)
        self.horizontalLayout_11.addWidget(self.groupBox_10)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_settings)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.cb_out_serial_port = QtWidgets.QComboBox(self.groupBox_8)
        self.cb_out_serial_port.setObjectName("cb_out_serial_port")
        self.horizontalLayout_12.addWidget(self.cb_out_serial_port)
        self.horizontalLayout_11.addWidget(self.groupBox_8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.btn_go = QtWidgets.QPushButton(self.tab_settings)
        font = QtGui.QFont()
        font.setPointSize(29)
        self.btn_go.setFont(font)
        self.btn_go.setObjectName("btn_go")
        self.verticalLayout_7.addWidget(self.btn_go)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.tab_settings)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        self.tabWidget.addTab(self.tab_settings, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 25))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFunctions = QtWidgets.QMenu(self.menubar)
        self.menuFunctions.setObjectName("menuFunctions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutOptions = QtWidgets.QVBoxLayout()
        self.verticalLayoutOptions.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayoutOptions.setObjectName("verticalLayoutOptions")
        self.lbl_options = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_options.sizePolicy().hasHeightForWidth())
        self.lbl_options.setSizePolicy(sizePolicy)
        self.lbl_options.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_options.setFont(font)
        self.lbl_options.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_options.setObjectName("lbl_options")
        self.verticalLayoutOptions.addWidget(self.lbl_options)
        self.verticalLayoutThreshould = QtWidgets.QVBoxLayout()
        self.verticalLayoutThreshould.setObjectName("verticalLayoutThreshould")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_record_raw_emg = QtWidgets.QPushButton(self.groupBox)
        self.btn_record_raw_emg.setObjectName("btn_record_raw_emg")
        self.verticalLayout_2.addWidget(self.btn_record_raw_emg)
        self.label_file_name = QtWidgets.QLabel(self.groupBox)
        self.label_file_name.setObjectName("label_file_name")
        self.verticalLayout_2.addWidget(self.label_file_name)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_output_name = QtWidgets.QLabel(self.groupBox)
        self.lbl_output_name.setObjectName("lbl_output_name")
        self.horizontalLayout_7.addWidget(self.lbl_output_name)
        self.lbl_output_value = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_output_value.sizePolicy().hasHeightForWidth())
        self.lbl_output_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_output_value.setFont(font)
        self.lbl_output_value.setObjectName("lbl_output_value")
        self.horizontalLayout_7.addWidget(self.lbl_output_value)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.btn_generate_training_file = QtWidgets.QPushButton(self.groupBox)
        self.btn_generate_training_file.setObjectName("btn_generate_training_file")
        self.verticalLayout_2.addWidget(self.btn_generate_training_file)
        self.btn_load_training_file = QtWidgets.QPushButton(self.groupBox)
        self.btn_load_training_file.setObjectName("btn_load_training_file")
        self.verticalLayout_2.addWidget(self.btn_load_training_file)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayoutThreshould.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_acquiring_status = QtWidgets.QLabel(self.groupBox_2)
        self.label_acquiring_status.setObjectName("label_acquiring_status")
        self.verticalLayout_3.addWidget(self.label_acquiring_status)
        self.label_plotting_status = QtWidgets.QLabel(self.groupBox_2)
        self.label_plotting_status.setObjectName("label_plotting_status")
        self.verticalLayout_3.addWidget(self.label_plotting_status)
        self.label_processing_status = QtWidgets.QLabel(self.groupBox_2)
        self.label_processing_status.setObjectName("label_processing_status")
        self.verticalLayout_3.addWidget(self.label_processing_status)
        self.label_classification_status = QtWidgets.QLabel(self.groupBox_2)
        self.label_classification_status.setObjectName("label_classification_status")
        self.verticalLayout_3.addWidget(self.label_classification_status)
        self.verticalLayoutThreshould.addWidget(self.groupBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutThreshould.addItem(spacerItem2)
        self.verticalLayoutCheckBoxes = QtWidgets.QVBoxLayout()
        self.verticalLayoutCheckBoxes.setObjectName("verticalLayoutCheckBoxes")
        self.label_channels = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_channels.setObjectName("label_channels")
        self.verticalLayoutCheckBoxes.addWidget(self.label_channels)
        self.cb_ch1 = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.cb_ch1.setObjectName("cb_ch1")
        self.verticalLayoutCheckBoxes.addWidget(self.cb_ch1)
        self.cb_ch3 = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.cb_ch3.setObjectName("cb_ch3")
        self.verticalLayoutCheckBoxes.addWidget(self.cb_ch3)
        self.cb_ch4 = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.cb_ch4.setObjectName("cb_ch4")
        self.verticalLayoutCheckBoxes.addWidget(self.cb_ch4)
        self.cb_ch2 = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.cb_ch2.setObjectName("cb_ch2")
        self.verticalLayoutCheckBoxes.addWidget(self.cb_ch2)
        self.verticalLayoutThreshould.addLayout(self.verticalLayoutCheckBoxes)
        self.verticalLayoutOptions.addLayout(self.verticalLayoutThreshould)
        self.verticalLayout.addLayout(self.verticalLayoutOptions)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionSimples = QtWidgets.QAction(MainWindow)
        self.actionSimples.setObjectName("actionSimples")
        self.actionIn_Plotter = QtWidgets.QAction(MainWindow)
        self.actionIn_Plotter.setObjectName("actionIn_Plotter")
        self.actionThread = QtWidgets.QAction(MainWindow)
        self.actionThread.setObjectName("actionThread")
        self.actionDesativado = QtWidgets.QAction(MainWindow)
        self.actionDesativado.setObjectName("actionDesativado")
        self.actionStartAcquisition = QtWidgets.QAction(MainWindow)
        self.actionStartAcquisition.setCheckable(False)
        self.actionStartAcquisition.setObjectName("actionStartAcquisition")
        self.actionStart_Recording = QtWidgets.QAction(MainWindow)
        self.actionStart_Recording.setObjectName("actionStart_Recording")
        self.actionStop_Recording = QtWidgets.QAction(MainWindow)
        self.actionStop_Recording.setObjectName("actionStop_Recording")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionFind_Serial_Port = QtWidgets.QAction(MainWindow)
        self.actionFind_Serial_Port.setObjectName("actionFind_Serial_Port")
        self.menuArquivo.addAction(self.actionStart_Recording)
        self.menuArquivo.addAction(self.actionStop_Recording)
        self.menuHelp.addAction(self.actionAbout)
        self.menuFunctions.addAction(self.actionStartAcquisition)
        self.menuFunctions.addSeparator()
        self.menuFunctions.addAction(self.actionFind_Serial_Port)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuFunctions.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.cb_features.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project Main"))
        self.label_replace.setText(_translate("MainWindow", "Here will be the chart"))
        self.lbl_status.setText(_translate("MainWindow", "Status:"))
        self.cb_chart_emg_on_off.setText(_translate("MainWindow", "Chart On/Off"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_EMG), _translate("MainWindow", "EMG"))
        self.label_features.setText(_translate("MainWindow", "Feature:"))
        self.checkBox.setText(_translate("MainWindow", "Visible"))
        self.label_replace_features.setText(_translate("MainWindow", "Here will be another the chart"))
        self.lbl_status_features.setText(_translate("MainWindow", "Status:"))
        self.cb_chart_features_on_off.setText(_translate("MainWindow", "Chart On/Off"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_features), _translate("MainWindow", "Features"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_classification), _translate("MainWindow", "Classification"))
        self.groupBox_f1.setTitle(_translate("MainWindow", "Finger 1: 0º"))
        self.groupBox_f2.setTitle(_translate("MainWindow", "Finger 2: 0º"))
        self.groupBox_f3.setTitle(_translate("MainWindow", "Finger 3: 0º"))
        self.groupBox_f4.setTitle(_translate("MainWindow", "Finger 4: 0º"))
        self.groupBox_f5.setTitle(_translate("MainWindow", "Finger 5: 0º"))
        self.groupBox_4.setTitle(_translate("MainWindow", "General"))
        self.btn_laser.setText(_translate("MainWindow", "Laser"))
        self.btn_reset_position.setText(_translate("MainWindow", "Open Hand"))
        self.btn_close_position.setText(_translate("MainWindow", "Close Hand"))
        self.btn_send_position.setText(_translate("MainWindow", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_controle_manuel), _translate("MainWindow", "Controle Manuel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Processing"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Input Serial Port"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Output Serial Port"))
        self.btn_go.setText(_translate("MainWindow", "Go!"))
        self.pushButton.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), _translate("MainWindow", "General Settings"))
        self.menuArquivo.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuFunctions.setTitle(_translate("MainWindow", "Options"))
        self.lbl_options.setText(_translate("MainWindow", "Options"))
        self.groupBox.setTitle(_translate("MainWindow", "Training"))
        self.btn_record_raw_emg.setText(_translate("MainWindow", "Record raw EMG file"))
        self.label_file_name.setText(_translate("MainWindow", "File: None"))
        self.lbl_output_name.setText(_translate("MainWindow", "Output:"))
        self.lbl_output_value.setText(_translate("MainWindow", "None"))
        self.btn_generate_training_file.setText(_translate("MainWindow", "Generate Training File"))
        self.btn_load_training_file.setText(_translate("MainWindow", "Load Training File"))
        self.label.setText(_translate("MainWindow", "Not Trained"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Status"))
        self.label_acquiring_status.setText(_translate("MainWindow", "Acquiring: Off"))
        self.label_plotting_status.setText(_translate("MainWindow", "Plotting: Off"))
        self.label_processing_status.setText(_translate("MainWindow", "Processing: Off"))
        self.label_classification_status.setText(_translate("MainWindow", "Classification: Off"))
        self.label_channels.setText(_translate("MainWindow", "Channels:"))
        self.cb_ch1.setText(_translate("MainWindow", "CH1"))
        self.cb_ch3.setText(_translate("MainWindow", "CH2"))
        self.cb_ch4.setText(_translate("MainWindow", "CH3"))
        self.cb_ch2.setText(_translate("MainWindow", "CH4"))
        self.actionSimples.setText(_translate("MainWindow", "Processamento"))
        self.actionIn_Plotter.setText(_translate("MainWindow", "In Plotter"))
        self.actionThread.setText(_translate("MainWindow", "Thread"))
        self.actionDesativado.setText(_translate("MainWindow", "Desativado"))
        self.actionStartAcquisition.setText(_translate("MainWindow", "Start Acquisition"))
        self.actionStart_Recording.setText(_translate("MainWindow", "Start Recording"))
        self.actionStop_Recording.setText(_translate("MainWindow", "Stop Recording"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionFind_Serial_Port.setText(_translate("MainWindow", "Find Serial Port"))

